spring:
  # 配置文件名称，用来标识不同环境的配置。由 spring.profiles.active 的值来决定使用哪组配置。
  ## 综合
  profiles: test
  redis:
    host: localhost
    port: 6379
    database: 0
  application:
    # 应用名称
    name: gateway-master
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      #  user product order 3个微服务
      routes:
        - id: app-service-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          uri: lb://app-service-user
        - id: app-service-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          uri: lb://app-service-product
        - id: app-service-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          uri: lb://app-service-order
        - id: app-service-mongo
          predicates:
            - Path=/mongo/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
          uri: lb://app-service-mongo


eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:30000/eureka/

logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug