server:
  port: 30013

# eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: localhost
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:30000/eureka/

# swagger2
swagger2.package: com.hdsx.appservice.mongo.service

# redis mysql druid
spring:
  application:
    name: app-service-mongo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hdsx?charSet=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
#      host: 39.101.219.33
#      port: 27017
#      database: hdsx
#      username: wei
#      password: 1234
#
      uri: mongodb://wei:1234@39.101.219.33:27017/hdsx?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false

# mybatis
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  config-location: classpath:mybatis-config.xml

debug: true
